packages:
  - "apps/*"
  - "!apps/admin"
  - "!apps/ai-orchestrator-service"
  - "!apps/crm-service"
  - "!apps/event-ingestion-service"
  - "!apps/landing"
  - "!apps/tenant"
  - "!apps/worker"
  - "!apps/workflow-service"
  - "packages/*"
  - "!packages/kafka"
  - "!packages/novu"
  - "tooling/*"
