module.exports = {
  apps: [
    {
      name: 'api-gateway',
      script: './apps/api-gateway/dist/main.js',
      instances: 2,
      exec_mode: 'cluster',
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'staging',
        PORT: 3001,
        LOG_LEVEL: 'debug',
      },
      error_file: './logs/api-gateway/error.log',
      out_file: './logs/api-gateway/out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'identity-service',
      script: './apps/identity-service/dist/main.js',
      instances: 2,
      exec_mode: 'cluster',
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'staging',
        PORT: 3002,
        IDENTITY_SERVICE_URL: 'http://localhost:3002',
        LOG_LEVEL: 'debug',
      },
      error_file: './logs/identity-service/error.log',
      out_file: './logs/identity-service/out.log',
      merge_logs: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'booking-service',
      script: './apps/booking-service/dist/main.js',
      instances: 2,
      exec_mode: 'cluster',
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'staging',
        PORT: 3003,
        BOOKING_SERVICE_URL: 'http://localhost:3003',
        LOG_LEVEL: 'debug',
      },
      error_file: './logs/booking-service/error.log',
      out_file: './logs/booking-service/out.log',
      merge_logs: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'payments-service',
      script: './apps/payments-service/dist/main.js',
      instances: 2,
      exec_mode: 'cluster',
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'staging',
        PORT: 3004,
        PAYMENTS_SERVICE_URL: 'http://localhost:3004',
        LOG_LEVEL: 'debug',
      },
      error_file: './logs/payments-service/error.log',
      out_file: './logs/payments-service/out.log',
      merge_logs: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'crm-service',
      script: './apps/crm-service/dist/main.js',
      instances: 2,
      exec_mode: 'cluster',
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'staging',
        PORT: 3005,
        CRM_SERVICE_URL: 'http://localhost:3005',
        LOG_LEVEL: 'debug',
      },
      error_file: './logs/crm-service/error.log',
      out_file: './logs/crm-service/out.log',
      merge_logs: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'dispatch-service',
      script: './apps/dispatch-service/dist/main.js',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'staging',
        PORT: 3006,
        DISPATCH_SERVICE_URL: 'http://localhost:3006',
        LOG_LEVEL: 'debug',
      },
      error_file: './logs/dispatch-service/error.log',
      out_file: './logs/dispatch-service/out.log',
      merge_logs: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'messaging-service',
      script: './apps/messaging-service/dist/main.js',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'staging',
        PORT: 3007,
        MESSAGING_SERVICE_URL: 'http://localhost:3007',
        LOG_LEVEL: 'debug',
      },
      error_file: './logs/messaging-service/error.log',
      out_file: './logs/messaging-service/out.log',
      merge_logs: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'event-ingestion-service',
      script: './apps/event-ingestion-service/dist/main.js',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'staging',
        PORT: 3013,
        LOG_LEVEL: 'debug',
      },
      error_file: './logs/event-ingestion-service/error.log',
      out_file: './logs/event-ingestion-service/out.log',
      merge_logs: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
  ],
};
